# Generated by Django 4.1 on 2024-03-10 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='DriverSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус водителя')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
            ],
            options={
                'verbose_name': 'Отметка водителя',
                'verbose_name_plural': 'Табель | Водители',
                'ordering': ['date', 'driver'],
            },
        ),
        migrations.CreateModel(
            name='Foreman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Прораб',
                'verbose_name_plural': 'Прорабы',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название техники')),
                ('type', models.CharField(max_length=255, verbose_name='Тип техники')),
                ('id_information', models.CharField(max_length=256, verbose_name='Идентификационная информация')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('attached_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.driver', verbose_name='Прикрепленный водитель')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Единица техники',
                'verbose_name_plural': 'Техника',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorkDaySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дени',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Telebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chat', models.CharField(max_length=128, verbose_name='id chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='TechnicSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус техники')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workdaysheet', verbose_name='Дата')),
                ('driver_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.driversheet', verbose_name='Табель водителя')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.technic', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Отметка техники',
                'verbose_name_plural': 'Табель | Техники',
                'ordering': ['date', 'technic'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Снабжение',
                'verbose_name_plural': 'Снабжение',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название переменной')),
                ('value', models.CharField(blank=True, max_length=512, null=True, verbose_name='Значение переменной')),
                ('flag', models.BooleanField(default=False, verbose_name='Флаг переменной')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные',
                'ordering': ['title', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Механик',
                'verbose_name_plural': 'Механики',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('foreman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.foreman', verbose_name='Прораб')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='driversheet',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workdaysheet', verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='driversheet',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.driver', verbose_name='Водитель'),
        ),
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, verbose_name='Адрес')),
                ('status', models.BooleanField(default=True, verbose_name='Статус объекта')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('foreman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.foreman', verbose_name='Прораб')),
            ],
            options={
                'verbose_name': 'Строительный объект',
                'verbose_name_plural': 'Строительные объекты',
                'ordering': ['address', 'foreman'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус заявки')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Примечание для объекта')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('construction_site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.constructionsite', verbose_name='Строительный объект')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workdaysheet', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Заявка на объект',
                'verbose_name_plural': 'Заявки на объект',
                'ordering': ['-date', 'construction_site'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTechnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет заявки')),
                ('isChecked', models.BooleanField(default=False, verbose_name='Проверена?')),
                ('id_orig_app', models.IntegerField(blank=True, null=True, verbose_name='Ид ApplicationTechnic')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('application_today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.applicationtoday', verbose_name='Заявка на объект')),
                ('technic_sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.technicsheet', verbose_name='Отметка техники')),
            ],
            options={
                'verbose_name': 'Заявка на технику',
                'verbose_name_plural': 'Заявки на технику',
            },
        ),
        migrations.CreateModel(
            name='ApplicationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2048, verbose_name='Описание')),
                ('isChecked', models.BooleanField(default=False, verbose_name='Проверенна?')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('application_today', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.applicationtoday', verbose_name='Заявка на объект')),
            ],
            options={
                'verbose_name': 'Заявка на материал',
                'verbose_name_plural': 'Заявка на материалы',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('isArchive', models.BooleanField(default=False, verbose_name='Архивирован?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
                'ordering': ['user'],
            },
        ),
    ]
