# Generated by Django 4.1 on 2024-03-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workdaysheet',
            options={'ordering': ['-date'], 'verbose_name': 'Рабочий день', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id_chat',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Telegram id chat'),
        ),
    ]
