# Generated by Django 4.1 on 2024-03-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_workdaysheet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technic',
            name='supervisor_technic',
            field=models.CharField(default='mechanic', max_length=100, verbose_name='Руководитель'),
        ),
    ]
