# Generated by Django 4.1 on 2024-03-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_driversheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicsheet',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workdaysheet', verbose_name='Дата'),
        ),
    ]
