# Generated by Django 4.1 on 2024-03-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_technicsheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicsheet',
            name='technic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.technic', verbose_name='Транспортное средство'),
        ),
    ]
