# Generated by Django 4.1 on 2024-03-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_technicsheet_technic'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
    ]
