# Generated by Django 4.1 on 2024-03-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_constructionsite_deleted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoday',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workdaysheet', verbose_name='Дата'),
        ),
    ]
