# Generated by Django 4.1 on 2024-04-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_applicationtoday_construction_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicsheet',
            name='count_application',
            field=models.IntegerField(default=0, verbose_name='Количество заявок (загруженость)'),
        ),
    ]
