# Generated by Django 4.1 on 2024-04-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_applicationtoday_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoday',
            name='status',
            field=models.CharField(blank=True, default='absent', max_length=255, null=True, verbose_name='Статус заявки'),
        ),
    ]
