# Generated by Django 4.1 on 2024-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_applicationtoday_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_show_absent_app',
            field=models.BooleanField(default=True, verbose_name='Показывать отсутствующие заявки'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_show_saved_app',
            field=models.BooleanField(default=True, verbose_name='Показывать сохраненные заявки'),
        ),
    ]
