# Generated by Django 4.1 on 2024-05-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_user_filter_technic_alter_user_filter_foreman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='filter_by',
        ),
        migrations.AddField(
            model_name='user',
            name='sort_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сортировать по:'),
        ),
    ]
