# Generated by Django 4.1 on 2024-05-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_user_filter_by_user_sort_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_show_panel',
            field=models.BooleanField(default=False, verbose_name='Показывать панель'),
        ),
    ]
