# Generated by Django 4.1 on 2024-06-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdaysheet',
            name='is_only_read',
            field=models.BooleanField(default=False, verbose_name="Режим 'Только чтение'"),
        ),
    ]
