# Generated by Django 4.1 on 2024-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_parameter_name_alter_parameter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Имя переменной'),
        ),
    ]
