# Generated by Django 4.1 on 2024-06-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_parameter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='permissions',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Разрешения'),
        ),
    ]
