# Generated by Django 5.0.6 on 2024-07-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_applicationtoday_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtoday',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Был отредактирован?'),
        ),
    ]
