# Generated by Django 4.1 on 2024-08-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_applicationmaterial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdaysheet',
            name='accept_mode',
            field=models.CharField(default='auto', max_length=32, verbose_name='Режим приема заявок'),
        ),
    ]
