# Generated by Django 4.1 on 2024-08-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_workdaysheet_accept_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdaysheet',
            name='is_only_read',
        ),
    ]
