# Generated by Django 4.1 on 2024-08-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_remove_workdaysheet_is_only_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="color_title",
            field=models.CharField(
                default="#000000", max_length=8, verbose_name="Цвет названия объекта"
            ),
        ),
    ]
