# Generated by Django 4.1 on 2024-08-26 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0032_user_color_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateDescForTechnic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=1024,
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "technic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.technic",
                        verbose_name="Техника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Templates для техники",
                "verbose_name_plural": "Template для техники",
            },
        ),
    ]
