# Generated by Django 4.1 on 2024-08-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0033_templatedescfortechnic"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatedescfortechnic",
            name="is_auto_mode",
            field=models.BooleanField(
                default=True, verbose_name="Автоматический режим"
            ),
        ),
        migrations.AddField(
            model_name="templatedescfortechnic",
            name="is_default_mode",
            field=models.BooleanField(default=False, verbose_name="Режим по умолчанию"),
        ),
    ]
