# Generated by Django 4.1 on 2024-09-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0034_templatedescfortechnic_is_auto_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="font_size",
            field=models.IntegerField(
                default=10, verbose_name="Размер шрифта для описания заявки"
            ),
        ),
    ]
