# Generated by Django 4.1 on 2025-01-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0035_user_font_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationmaterial",
            options={
                "ordering": ["application_today"],
                "verbose_name": "Заявка на материал",
                "verbose_name_plural": "Заявка на материалы",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationtechnic",
            options={
                "ordering": ["application_today", "technic_sheet"],
                "verbose_name": "Заявка на технику",
                "verbose_name_plural": "Заявки на технику",
            },
        ),
        migrations.AlterModelOptions(
            name="parameter",
            options={
                "ordering": ["title"],
                "verbose_name": "Переменная",
                "verbose_name_plural": "Переменные",
            },
        ),
        migrations.AlterModelOptions(
            name="technic",
            options={
                "ordering": ["title", "attached_driver"],
                "verbose_name": "Единица техники",
                "verbose_name_plural": "Техника",
            },
        ),
        migrations.AlterModelOptions(
            name="templatedescfortechnic",
            options={
                "ordering": ["technic"],
                "verbose_name": "Templates для техники",
                "verbose_name_plural": "Template для техники",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["last_name"],
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
